### ISSUE TITLE
a mistake in rotary embbeding

### ISSUE THREAD

**Issue by chenht2010** [lucidrains/voicebox-pytorch#13]
https://github.com/lucidrains/voicebox-pytorch/blob/47e31803db3ad8df93bf29a91007b4f45eba00fd/voicebox_pytorch/voicebox_pytorch.py#L236

**Comment by fd873630** [comment]
I'm testing with a toy dataset.

The previous code was not trained.

Changing to this code seems to be learning well from the first epoch.

Awesome! Thank you so much.
