### ISSUE TITLE
Pre-trained model weights

### ISSUE THREAD

**Issue by Hades32** [lucidrains/voicebox-pytorch#18]
When this project is done (or at least in a beta state), will pre-trained model weights be released too?

**Comment by fakerybakery** [comment]
Hi @lucidrains, I was wondering if there are pre-trained models available now.

Commit `8b3d153` had the commit message:

> @lucasnewman got it working end to end with spear tts. sounds really good

Does this mean that @lucasnewman was able to create pre-trained models?

Thanks in advance!

**Comment by lucidrains** [comment]
@fakerybakery no. It means the rocket flies, but then one still needs to shoot for the moon with a push with more data and compute. but seeing some liftoff is better than none.

**Comment by lucidrains** [comment]
hope that makes sense
