### ISSUE TITLE
Audio samples?

### ISSUE THREAD

**Issue by blx0102** [lucidrains/voicebox-pytorch#28]
Great work here!
It seem you have already combined voicebox with spear-tts, could you provide some result audio samples?

**Comment by lucidrains** [comment]
@blx0102 Lucas already has shared some early audio samples with me. Seems to work

**Comment by lucasnewman** [comment]
@blx0102 It's still early days here as we dial in the training and inference, but here's an [early sample](https://s3.amazonaws.com/lucasnewman.datasets/voicebox/voicebox-sample.wav) with the [prompt](https://s3.amazonaws.com/lucasnewman.datasets/voicebox/voicebox-semantic-prompt.wav) that was used for the semantic tokens. This is a 93M param model that's done about ~200k training steps @ effective batch size of 16 on LibriTTS-R.
