### ISSUE TITLE
VoiceBox Training 

### ISSUE THREAD

**Issue by yiwei0730** [lucidrains/voicebox-pytorch#33]
If I want to train this package of models, do I need to run spear-tts first to obtain the text-to-semantic model before running voicebox, or can I directly run the voicebox semantic model and train the main model together?

**Comment by lucidrains** [comment]
yes, at the moment it requires three models across three repositories. so unless you are an exceptional engineer or scientist (like Lucas), you will have trouble getting it all working in concert

give me more time to think about how to weave this all together

**Comment by lucidrains** [comment]
@yiwei0730 on the other hand, if you want to test out unconditional training, then you should be able to get working quite easily with just the base model in this repository alone

**Comment by lucidrains** [comment]
to answer your original question, you need a trained text-to-semantic model from spear-tts, which requires yet another 3 step training process
