### ISSUE TITLE
Loss calculation

### ISSUE THREAD

**Issue by YKoustubhRao** [lucidrains/voicebox-pytorch#34]
I think, cond_mask_with_pad_dim should also be applied to target (flow) while calculating loss.

**Comment by lucidrains** [comment]
@YKoustubhRao it is [here](https://github.com/lucidrains/voicebox-pytorch/blob/main/voicebox_pytorch/voicebox_pytorch.py#L1072) `cond_mask_with_pad_dim` is derived from `cond_mask`
